### ISSUE TITLE
Incorrect number of users in top bar

### ISSUE THREAD

**Issue by ghost** [nunof07/discourse-mumble#1]
Great tool!  

Adding a single user to the server, the indicator says there were two users.

{
  "id": 1,
  "name": "",
  "root": {
    "channels": [],
    "description": "The Mumbler server is provided by the <a href=\"http://forum.serrated.us/\">Serrated Guild</a>.",
    "id": 0,
    "links": [],
    "name": "Root",
    "parent": -1,
    "position": 0,
    "temporary": false,
    "users": [
      {
        "channel": 0,
        "comment": "",
        "deaf": false,
        "idlesecs": 239,
        "mute": false,
        "name": "SuperUser",
        "prioritySpeaker": false,
        "recording": false,
        "selfDeaf": false,
        "selfMute": false,
        "session": 1,
        "suppress": true,
        "userid": 0
      }
    ]
  }
}

**Comment by ghost** [comment]
When 2 came online, the number turned to 4.  So it may be doubling it.

**Comment by nunof07** [comment]
Thanks, I will check it.

Today and tomorrow I don't have time, but I will have a look on Monday.

**Comment by ghost** [comment]
I think the issue is that the users in the root category are being counted twice.

First here:
var count = root.users ? root.users.length : root.user ? (Ember.isArray(root.user) ? root.user.length : 1): 0,

and then again here iterate(root);

Hope that helps!

**Comment by nunof07** [comment]
You are right. That's probably it. Thanks.

**Comment by nunof07** [comment]
Should be fixed now with the latest release. Let me know if you still have any problem.
