### ISSUE TITLE
Request to hide empty channels

### ISSUE THREAD

**Issue by ghost** [nunof07/discourse-mumble#2]
In large systems, there will be a great number of channels.  It would be awesome if the empty channels  did not show up in the discourse menu.

Another nice option would have been to hide the channels altogether form the admin panel, but that is no big deal.

**Comment by nunof07** [comment]
Makes sense. I will try to add a new setting to control whether to display empty channels.

**Comment by nunof07** [comment]
The latest release has a new setting to control this. By default it will hide empty channels.
