### ISSUE TITLE
Messages icon in wrong the place

### ISSUE THREAD

**Issue by ghost** [nunof07/discourse-mumble#3]
![capture](https://cloud.githubusercontent.com/assets/1703329/9700918/e51d878e-53e3-11e5-8ae7-6f1b11d46db2.PNG)

The standard messages+ notification number has shifted one icon to the left, It is supposed to be over the right-most icon where you check the messages.

Sry to write so many on this, but I am hoping you might be able to address these at one time.

**Comment by nunof07** [comment]
I was testing on a clean install, so I never noticed this.

I will have a look together with the other issues. Thanks for the heads up.

**Comment by ghost** [comment]
I just noticed that it is only the new IM indicator (green) which appears to the upper left of the shield that is off.  The right-side indicator for various alerts is in the right place.

**Comment by nunof07** [comment]
This should be fixed with the latest release. Let me know if you still have this issue.

**Comment by ghost** [comment]
I tested issues #1, #2 and #3.   It is looking just awesome!  Thank you so much!

**Comment by nunof07** [comment]
Great! Thanks.
