### ISSUE TITLE
not compatible with latest discourse

### ISSUE THREAD

**Issue by verymilan** [nunof07/discourse-mumble#4]
Please make it compatible with the current discourse version. :)

**Comment by nunof07** [comment]
Sorry, I don't personally use Discourse or work with Ruby and it's a pain in the butt to setup the development machine.

I can accept pull requests but at this point I don't see myself working on this anymore.

**Comment by verymilan** [comment]
This plugin is very important to me so i would appriciate help for debugging and fixing it.
I already set up a discourse in development for testing but was yet unable to understand what is where wrong and what should be different - and how.
I hoped about helpfol deprication warnings but there wheren't any.

I also would contribute back... found a Firefox extention for debugging Ember but Discourse loads not far enough with the plugin installed so it does not able to detect an Ember site.

However - i would work myself in as soon as i know how to start.... .
You already wrote the plugin so you might be able to help me out there. :)

Beside - i set it up in under five minutes (well my network connection was way slower so it took hours but the actual setup was done in under five minutes lol.) 
If you don't wanna work on this anymore, please help me to work on it so i can get rid of this shitty 3rdparty script connected to an external provider i am currently using.

**Comment by nunof07** [comment]
So the plugin prevents Discourse from starting? Is there any error message?

**Comment by verymilan** [comment]
Starting itself works, the browser console tells about `Ember.View` not defined, and the page is just white.

**Comment by nunof07** [comment]
I think the `Ember.View` is only used for the count: https://github.com/nunof07/discourse-mumble/blob/ba9b89fbd3d02e1970633244c04ef3b20b70a1a9/assets/javascripts/discourse/views/connectors/header-before-notifications/mumble-count.js.es6

Maybe you can try removing it from the plugin to see if the rest works.

**Comment by verymilan** [comment]
Okey, this works so far, i was able to set the settings but the ui integration is missing (as expected, right?).
Also i didn't see a networkactivity to the CVP service - or does this run in the background from server-side? (the adress is [correct](https://commsviewer.com/api/commsviewer.php?cvserverid=15132&callback=Ext.ux.JSONP.callback) and provides json)
Edit: seems to run by the plugin.rb - nevermind

**Comment by nunof07** [comment]
Where you using this plugin before? Do you have any idea when it started breaking? 

Might it be due to the Ember update done on Discourse 1.7? It appears the `View` class has been removed in Ember 2.x. Not sure which version is running on Discourse. See http://emberjs.com/deprecations/v1.x/#toc_ember-view

**Comment by verymilan** [comment]
Sorry for my late response!
No, i did not have it before, this is actually my first time with your plugin. :) 
My idea are actually ember deprications - thanks for providing the link, i searched hard for this and just didn't found such a page. I will play around with it soon.

Beside - i did not yet understand how ember knows where to place elements.
I read a bunch in different Discourse plugins but it didn't really make sense.
Or is it https://github.com/nunof07/discourse-mumble/blob/master/assets/javascripts/discourse/templates/components/mumble-icon.hbs#L1 ?
I only played with the id's (looking also wrong) but if it does not match the current ember it is clear that it won't work. :D 

Edit: my mentioned line is an actual problem for me as a beginner since it looks(!) like it is not the common way you're used. Hm.

**Comment by nunof07** [comment]
Not sure if I understand what you are asking. What do you mean by it's not the common way to do?

Please bear in mind that my knowledge in Discourse and Ember is also limited. I only worked on it for this plugin, so I hope I don't give any false information.

The templates and components are matched by name. So the ember component `mumble-icon.js.es6` is matched with the template `mumble-icon.hbs`. The `mumble-icon` template is using another component `header-dropdown` to render the dropdown.

Discourse has plugin outlets and path conventions that you can use to inject stuff.

**Comment by Adorfer** [comment]
So is there some kind ot pull request as patch, so it can be used again in current deployments?

**Comment by nunof07** [comment]
Not that I know of.

I will gladly accept any pull requests that are submitted.

I don't have time to maintain this at the moment.

**Comment by Adorfer** [comment]
Just for notice, if somebody likes to fix it, i set up a 100USD bounty for it. Feel free to go for it: 
https://meta.discourse.org/t/paid-100usd-bounty-to-fix-mumble-plugin/73904

**Comment by nunof07** [comment]
Fixed by #5. Please confirm, I haven't tested it.

**Comment by verymilan** [comment]
Yay it works!

**Comment by Adorfer** [comment]
bounty paid. Thanks for the fish!
